@startuml
'Sequence Diagram for Execute Register.
Participant ":Player" as Player
Participant ":Client" as Client
Participant ":Server" as Server


autonumber
Player --> Client : Execute Register
Client -> Client : Executes Register
Client -> Server : pushGameUpdate(gameID, PlayerDTO)
Server -> Server : Save state
Client -->> Server : getGameUpdate(gameID,currentVersion)
Client ->> Client : replaceBoard(board, currentVersion)
Client --> Player : Display board

@enduml