@startuml
'https://plantuml.com/sequence-diagram
Actor ":Player" as Player
Participant ":Client" as Client
Participant ":Server" as Server

autonumber
Player -> Client : LeaveGame()
Client -> Server : leaveGame(gameID, PlayerDTO)
Server -> Server : deletePlayer(gameID, Player)
Server --> Client : "Player removed"
Client -> Client : Join BoardUpdateThread
Client -> Player : Close view



@enduml