@startuml
'https://plantuml.com/sequence-diagram
Participant ":Player" as Player
Participant ":Client" as Client
Participant ":Server" as Server

autonumber
Player -> Client : Leave Game
Client -> Server : Remove Player
Server -> Server : Removes Player
Server --> Client : "Player removed"
Client -> Client : Join BoardUpdateThread
Client -> Player : Close view



@enduml